### ISSUE TITLE
Please add example how to use zstd-codec with dictionary

### ISSUE THREAD

**Issue by progamer71** [yoshihitoh/zstd-codec#1]
Assume I already have trained dictionary.
How to load trained dictionary in the browser and do decompress/compress with loaded dictionary.

Thanks you.

**Comment by yoshihitoh** [comment]
Hello, thanks for making the first issue!

Unfortunately, dictionary interfaces are not ready yet.
I'll implement it in this weekend.

signatures will be...
```
function compress(data: Uint8Array, dict: Uint8Array) -> Uint8Array; // return value is compressed  bytes
function decompress(compressed: Uint8Array, dict: Uint8Array) -> Uint8Array; // return value is original bytes
```

**Comment by progamer71** [comment]
Thanks you for you great work.
I will test with my use case and give you a feedback.

**Comment by yoshihitoh** [comment]
@progamer71  Hi!
I added dictionary interfaces for simple API, and published `0.0.5` to NPM.
If you need streaming API, please wait next update (will be next weekend.)

```javascript
// compress
const compressed_bytes = simple.compressUsingDict(content_bytes, dict_bytes, compression_level);

// decompress
const content_bytes = simple.decompressUsingDict(compressed_bytes, dict_bytes);
```

Please see [js/example/dist/index.html](https://github.com/yoshihitoh/zstd-codec/blob/develop/js/example/dist/index.html#L38-L56) .

I will add dictionary class on next update, and change APIs to use dictionary class instead of TypedArray.

**Comment by yoshihitoh** [comment]
@progamer71 hello
I published dictionary APIs for streaming mode.
Please update to `0.0.7` .

You can use dictionary on streaming mode by calling `beginUsingDict` instead of `begin` .
See [js tests](https://github.com/yoshihitoh/zstd-codec/pull/4/files#diff-5794f41e17f69e4972a66c90b2d58109) for example usage. I will update README later 😄

**Comment by progamer71** [comment]
@yoshihitoh 
I run an example perfectly.
Excellent work.

**Comment by yoshihitoh** [comment]
@progamer71 
Thanks for your testing!
I'm really new to JavaScript, if you have idea to improve zstd-codec, please create issues again.
