### ISSUE TITLE
Streaming API for piping

### ISSUE THREAD

**Issue by josephrocca** [yoshihitoh/zstd-codec#19]
With `node-zstd` we can do something like this:

```js
const fetch = require('node-fetch');
const decompressor = require('node-zstd').decompressStream();
let stream = (await fetch('https://files.pushshift.io/reddit/comments/RC_2018-12.zst').then(r => r.body)).pipe(decompressor);
stream.on('data', function(chunk) {
  // process decompressed chunk
});
```

Is there a way to pass a stream to this module like in the above example? If not, any chance that something like this could be implemented? `node-zstd` seems to have a strange memory-spiking problem that makes it unusable for my use case.

**Comment by yoshihitoh** [comment]
Hello @josephrocca !
Sorry for the too late response.

Unfortunately, zstd-codec does not support Node.js' Streaming API.
I'm working to improve zstd-codec, but it is really difficult to support both Node.js and WebAssembly because there is no sophisticated build system :(
(GYP would work for it, but I don't want to learn about the complex syntaxes...)

Now I'm planning to use Rust and its bindgen and wasm-bindgen.
I'm going to implement Node.js Streaming API if this approach would work.

**Comment by yoshihitoh** [comment]
Closing the issue, Feel free to reopen this.

**Comment by 0Ams** [comment]
@yoshihitoh  Is there any further progress on that?
